[project]
name = "kaigitai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "pytest>=9.0.1",
    "jsonschema>=4.23.0",
    "flask>=3.0.3",
    "frozen-flask>=1.0.2",
]
